<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SaltboxGames.Core</RootNamespace>
    <Description>Source-distributed C# library with optional MemoryPack and ZLinq support.</Description>
    <EnableMemoryPack>false</EnableMemoryPack> <!-- MemoryPack opt-in toggle -->
    <EnableZLinq>false</EnableZLinq> <!-- ZLinq opt-in toggle -->
    <LangVersion>12</LangVersion> 
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="./Runtime" />
  </ItemGroup>
  
  <!-- ZLINQ -->
  <ItemGroup Condition="'$(EnableZLinq)' == 'true'">
    <PackageReference Include="ZLinq" Version="1.5.1" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(EnableZLinq)' == 'true'">
    <DefineConstants>$(DefineConstants);ZLINQ</DefineConstants>
  </PropertyGroup>
  <!-- ZLINQ -->

  <!-- MEMORY_PACK -->
  <ItemGroup Condition="'$(EnableMemoryPack)' == 'true'">
    <PackageReference Include="MemoryPack" Version="1.21.4" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(EnableMemoryPack)' == 'true'">
    <DefineConstants>$(DefineConstants);MEMORY_PACK</DefineConstants>
  </PropertyGroup>
  <!-- MEMORY_PACK -->

</Project>
